FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app

RUN apk add --no-cache python3 make g++ \
  && ln -sf python3 /usr/bin/python

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist
CMD ["npm", "run", "start:prod"]