input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["reservations"]
    group_id => "logstash-reservations"
    auto_offset_reset => "earliest"
    codec => "json"
  }
}

filter {
  mutate {
    rename => { "[reservation][id]" => "reservation_id" }
  }

  if [ts] {
    date {
      match => ["ts", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "reservations-v1"
    document_id => "%{reservation_id}"
  }
  stdout { codec => rubydebug }
}