FROM kong:3.6

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    git luarocks \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN luarocks install lua-resty-openidc
RUN luarocks install lua-resty-session

RUN git clone https://github.com/revomatico/kong-oidc.git /tmp/kong-oidc \
    && cp -r /tmp/kong-oidc/kong/plugins/oidc /usr/local/share/lua/5.1/kong/plugins/ \
    && rm -rf /tmp/kong-oidc

USER kong